/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AnswerRouteImport } from './routes/answer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLogFeedbackRouteImport } from './routes/api/public/log-feedback'
import { Route as ApiPublicLogAnalyticsRouteImport } from './routes/api/public/log-analytics'
import { Route as ApiPublicAskRouteImport } from './routes/api/public/ask'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerRoute = AnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogFeedbackRoute = ApiPublicLogFeedbackRouteImport.update({
  id: '/api/public/log-feedback',
  path: '/api/public/log-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogAnalyticsRoute = ApiPublicLogAnalyticsRouteImport.update({
  id: '/api/public/log-analytics',
  path: '/api/public/log-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAskRoute = ApiPublicAskRouteImport.update({
  id: '/api/public/ask',
  path: '/api/public/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/log-analytics': typeof ApiPublicLogAnalyticsRoute
  '/api/public/log-feedback': typeof ApiPublicLogFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/log-analytics': typeof ApiPublicLogAnalyticsRoute
  '/api/public/log-feedback': typeof ApiPublicLogFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/log-analytics': typeof ApiPublicLogAnalyticsRoute
  '/api/public/log-feedback': typeof ApiPublicLogFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answer'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/settings'
    | '/welcome'
    | '/api/public/ask'
    | '/api/public/log-analytics'
    | '/api/public/log-feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answer'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/settings'
    | '/welcome'
    | '/api/public/ask'
    | '/api/public/log-analytics'
    | '/api/public/log-feedback'
  id:
    | '__root__'
    | '/'
    | '/answer'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/settings'
    | '/welcome'
    | '/api/public/ask'
    | '/api/public/log-analytics'
    | '/api/public/log-feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerRoute: typeof AnswerRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicAskRoute: typeof ApiPublicAskRoute
  ApiPublicLogAnalyticsRoute: typeof ApiPublicLogAnalyticsRoute
  ApiPublicLogFeedbackRoute: typeof ApiPublicLogFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer': {
      id: '/answer'
      path: '/answer'
      fullPath: '/answer'
      preLoaderRoute: typeof AnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-feedback': {
      id: '/api/public/log-feedback'
      path: '/api/public/log-feedback'
      fullPath: '/api/public/log-feedback'
      preLoaderRoute: typeof ApiPublicLogFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-analytics': {
      id: '/api/public/log-analytics'
      path: '/api/public/log-analytics'
      fullPath: '/api/public/log-analytics'
      preLoaderRoute: typeof ApiPublicLogAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask': {
      id: '/api/public/ask'
      path: '/api/public/ask'
      fullPath: '/api/public/ask'
      preLoaderRoute: typeof ApiPublicAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerRoute: AnswerRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicAskRoute: ApiPublicAskRoute,
  ApiPublicLogAnalyticsRoute: ApiPublicLogAnalyticsRoute,
  ApiPublicLogFeedbackRoute: ApiPublicLogFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
