/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnswerRouteImport } from './routes/answer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CbtRouteImport } from './routes/cbt'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LearningProfileRouteImport } from './routes/learning-profile'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PastQuestionsRouteImport } from './routes/past-questions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicAskRouteImport } from './routes/api/public/ask'
import { Route as ApiPublicCbtRouteImport } from './routes/api/public/cbt'
import { Route as ApiPublicGuideRouteImport } from './routes/api/public/guide'
import { Route as ApiPublicLogAnalyticsRouteImport } from './routes/api/public/log-analytics'
import { Route as ApiPublicLogFeedbackRouteImport } from './routes/api/public/log-feedback'
import { Route as ApiPublicPastQuestionsRouteImport } from './routes/api/public/past-questions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerRoute = AnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CbtRoute = CbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningProfileRoute = LearningProfileRouteImport.update({
  id: '/learning-profile',
  path: '/learning-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PastQuestionsRoute = PastQuestionsRouteImport.update({
  id: '/past-questions',
  path: '/past-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAskRoute = ApiPublicAskRouteImport.update({
  id: '/api/public/ask',
  path: '/api/public/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCbtRoute = ApiPublicCbtRouteImport.update({
  id: '/api/public/cbt',
  path: '/api/public/cbt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuideRoute = ApiPublicGuideRouteImport.update({
  id: '/api/public/guide',
  path: '/api/public/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogAnalyticsRoute = ApiPublicLogAnalyticsRouteImport.update({
  id: '/api/public/log-analytics',
  path: '/api/public/log-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogFeedbackRoute = ApiPublicLogFeedbackRouteImport.update({
  id: '/api/public/log-feedback',
  path: '/api/public/log-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPastQuestionsRoute = ApiPublicPastQuestionsRouteImport.update({
  id: '/api/public/past-questions',
  path: '/api/public/past-questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/answer': typeof AnswerRoute
  '/auth': typeof AuthRoute
  '/cbt': typeof CbtRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/learning-profile': typeof LearningProfileRoute
  '/mcp': typeof McpRoute
  '/notebook': typeof NotebookRoute
  '/onboarding': typeof OnboardingRoute
  '/past-questions': typeof PastQuestionsRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/cbt': typeof ApiPublicCbtRoute
  '/api/public/guide': typeof ApiPublicGuideRoute
  '/api/public/log-analytics': typeof ApiPublicLogAnalyticsRoute
  '/api/public/log-feedback': typeof ApiPublicLogFeedbackRoute
  '/api/public/past-questions': typeof ApiPublicPastQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/answer': typeof AnswerRoute
  '/auth': typeof AuthRoute
  '/cbt': typeof CbtRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/learning-profile': typeof LearningProfileRoute
  '/mcp': typeof McpRoute
  '/notebook': typeof NotebookRoute
  '/onboarding': typeof OnboardingRoute
  '/past-questions': typeof PastQuestionsRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/cbt': typeof ApiPublicCbtRoute
  '/api/public/guide': typeof ApiPublicGuideRoute
  '/api/public/log-analytics': typeof ApiPublicLogAnalyticsRoute
  '/api/public/log-feedback': typeof ApiPublicLogFeedbackRoute
  '/api/public/past-questions': typeof ApiPublicPastQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/answer': typeof AnswerRoute
  '/auth': typeof AuthRoute
  '/cbt': typeof CbtRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/learning-profile': typeof LearningProfileRoute
  '/mcp': typeof McpRoute
  '/notebook': typeof NotebookRoute
  '/onboarding': typeof OnboardingRoute
  '/past-questions': typeof PastQuestionsRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/cbt': typeof ApiPublicCbtRoute
  '/api/public/guide': typeof ApiPublicGuideRoute
  '/api/public/log-analytics': typeof ApiPublicLogAnalyticsRoute
  '/api/public/log-feedback': typeof ApiPublicLogFeedbackRoute
  '/api/public/past-questions': typeof ApiPublicPastQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/answer'
    | '/auth'
    | '/cbt'
    | '/history'
    | '/home'
    | '/learning-profile'
    | '/mcp'
    | '/notebook'
    | '/onboarding'
    | '/past-questions'
    | '/settings'
    | '/upgrade'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ask'
    | '/api/public/cbt'
    | '/api/public/guide'
    | '/api/public/log-analytics'
    | '/api/public/log-feedback'
    | '/api/public/past-questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/answer'
    | '/auth'
    | '/cbt'
    | '/history'
    | '/home'
    | '/learning-profile'
    | '/mcp'
    | '/notebook'
    | '/onboarding'
    | '/past-questions'
    | '/settings'
    | '/upgrade'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ask'
    | '/api/public/cbt'
    | '/api/public/guide'
    | '/api/public/log-analytics'
    | '/api/public/log-feedback'
    | '/api/public/past-questions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/answer'
    | '/auth'
    | '/cbt'
    | '/history'
    | '/home'
    | '/learning-profile'
    | '/mcp'
    | '/notebook'
    | '/onboarding'
    | '/past-questions'
    | '/settings'
    | '/upgrade'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ask'
    | '/api/public/cbt'
    | '/api/public/guide'
    | '/api/public/log-analytics'
    | '/api/public/log-feedback'
    | '/api/public/past-questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnswerRoute: typeof AnswerRoute
  AuthRoute: typeof AuthRoute
  CbtRoute: typeof CbtRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LearningProfileRoute: typeof LearningProfileRoute
  McpRoute: typeof McpRoute
  NotebookRoute: typeof NotebookRoute
  OnboardingRoute: typeof OnboardingRoute
  PastQuestionsRoute: typeof PastQuestionsRoute
  SettingsRoute: typeof SettingsRoute
  UpgradeRoute: typeof UpgradeRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAskRoute: typeof ApiPublicAskRoute
  ApiPublicCbtRoute: typeof ApiPublicCbtRoute
  ApiPublicGuideRoute: typeof ApiPublicGuideRoute
  ApiPublicLogAnalyticsRoute: typeof ApiPublicLogAnalyticsRoute
  ApiPublicLogFeedbackRoute: typeof ApiPublicLogFeedbackRoute
  ApiPublicPastQuestionsRoute: typeof ApiPublicPastQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer': {
      id: '/answer'
      path: '/answer'
      fullPath: '/answer'
      preLoaderRoute: typeof AnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt': {
      id: '/cbt'
      path: '/cbt'
      fullPath: '/cbt'
      preLoaderRoute: typeof CbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-profile': {
      id: '/learning-profile'
      path: '/learning-profile'
      fullPath: '/learning-profile'
      preLoaderRoute: typeof LearningProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-questions': {
      id: '/past-questions'
      path: '/past-questions'
      fullPath: '/past-questions'
      preLoaderRoute: typeof PastQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask': {
      id: '/api/public/ask'
      path: '/api/public/ask'
      fullPath: '/api/public/ask'
      preLoaderRoute: typeof ApiPublicAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cbt': {
      id: '/api/public/cbt'
      path: '/api/public/cbt'
      fullPath: '/api/public/cbt'
      preLoaderRoute: typeof ApiPublicCbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guide': {
      id: '/api/public/guide'
      path: '/api/public/guide'
      fullPath: '/api/public/guide'
      preLoaderRoute: typeof ApiPublicGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-analytics': {
      id: '/api/public/log-analytics'
      path: '/api/public/log-analytics'
      fullPath: '/api/public/log-analytics'
      preLoaderRoute: typeof ApiPublicLogAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-feedback': {
      id: '/api/public/log-feedback'
      path: '/api/public/log-feedback'
      fullPath: '/api/public/log-feedback'
      preLoaderRoute: typeof ApiPublicLogFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/past-questions': {
      id: '/api/public/past-questions'
      path: '/api/public/past-questions'
      fullPath: '/api/public/past-questions'
      preLoaderRoute: typeof ApiPublicPastQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnswerRoute: AnswerRoute,
  AuthRoute: AuthRoute,
  CbtRoute: CbtRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LearningProfileRoute: LearningProfileRoute,
  McpRoute: McpRoute,
  NotebookRoute: NotebookRoute,
  OnboardingRoute: OnboardingRoute,
  PastQuestionsRoute: PastQuestionsRoute,
  SettingsRoute: SettingsRoute,
  UpgradeRoute: UpgradeRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAskRoute: ApiPublicAskRoute,
  ApiPublicCbtRoute: ApiPublicCbtRoute,
  ApiPublicGuideRoute: ApiPublicGuideRoute,
  ApiPublicLogAnalyticsRoute: ApiPublicLogAnalyticsRoute,
  ApiPublicLogFeedbackRoute: ApiPublicLogFeedbackRoute,
  ApiPublicPastQuestionsRoute: ApiPublicPastQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
